src/data.py, src/sites.py, tests/integration_test.py, tests/sites_test.py
This PR refactors the sites integration test to put all data derived from a known structure into a `SitesData` class.
=> Add SitesData class

src/dashboard/run.py
Tk window does not have to be created for filepicker, not creating the window makes matpotlib happy
=> Make dashboard filepicker more stable

src/calculate/tracer.py, src/constants.py, src/plots/jumps.py, src/sites.py, tests/integration_test.py
This PR calculates the jump diffusivity.
=> Calculate jump diffusivity

pyproject.toml, src/sites.py
Use a KDtree to match atoms to sites, this gives an approx 2x speedup over calculating all distances.
=> Optimize site search

src/sites.py, tests/integration_test.py
This PR updates the values in the integration test after the changes in #52. It also fixes a crash because the labels syntax has changed.
=> Fix integration test

src/calculate/tracer.py, src/calculate/vibration.py, src/constants.py, src/sites.py, tests/integration_test.py, tests/vibration_test.py
=> Store units in FloatWithUnit and use `scipy.constants`

src/sites.py, tests/integration_test.py
This PR adds an implementation for calculating possible collective jumps.
=> Add implementation for calculating collective jumps

pyproject.toml
=> Require pymatgen-2023.7.14

src/plots/jumps.py, src/sites.py
This PR adds some jumps plots.
It's a 1x1 matrix, so not very interesting to look at 😅
=> Add jumps vs time histogram

pyproject.toml, src/rdf.py, tests/integration_test.py
This PR adds the rdf calculation to GEMDAT. So far I have the total RDF per element. It's quite slow (~35 s), because it's not obvious to me how to vectorize it. We need to 1) calculate all pairwise distances for each time step, 2) group the distances by element, and 3) track the transition state as well.
The last step is super tricky, the code I have for it is super ugly and I'm not 100% sure I got it right.
Closes #57
=> Calculate and plot rdf

src/dashboard/_shared.py, src/dashboard/run.py, src/rdf.py
=> Add Radial Distribution Function plots to dashboard

src/plots/jumps.py
=> Fix plot labels

src/sites.py, tests/integration_test.py
=> Fix assignment of `atom_sites_to/from`

pyproject.toml
=> Bump pymatgen pin to >= 2023.8.10

src/dashboard/run.py
This PR tweaks the layout of the dashboard a little bit.
=> Tweak dashboard layout

src/caching.py, src/collective.py, src/dashboard/run.py, src/legacy.py, src/rdf.py, src/simulation_metrics.py, src/sites.py, src/transitions.py, src/volume.py, tests/integration/trajectory_test.py
=> Fix cache memory leak

tests/integration/sites_test.py
This PR makes the integration tests a little bit more exhaustive, which was on of the unfulfilled requirements for #80.
=> Make integration tests more exhaustive

docs/api/gemdat_collective.md, docs/api/gemdat_transitions.md, mkdocs.yml, src/gemdat/collective.py, src/gemdat/io.py, src/gemdat/transitions.py
=> Add missing modules to docs

src/gemdat/trajectory.py, tests/integration/trajectory_test.py
Closes #133 
```python
>>> trajectory
Full Formula (Li48 P8 S40 Br8)
Reduced Formula: Li6PS5Br
abc   :  19.873726   9.919447   9.916454
angles:  90.214114  90.859135  89.950474
pbc   :       True       True       True
Constant lattice (True)
Sites (104)
Time steps (3750)
```
=> Add repr to `Trajectory`

README.md
This PR adds new shiny PyPI badges to the Readme.
=> Add PyPI badges to readme

src/gemdat/data/mno2_lambda.cif
=> Fix known material MnO2

src/gemdat/sites.py, src/gemdat/trajectory.py
Use `constant_lattice=False` to read NPT data.
Closes #153
=> Add support for loading NPT data with varying lattice

src/gemdat/trajectory.py, tests/playwright_test.py
=> Fix hash function

src/gemdat/dashboard/run.py, src/gemdat/volume.py
This PR adds the density plot to the dashboard.
Closes #124
=> Add density plot to dashboard

.pre-commit-config.yaml, tests/playwright_test.py, tools/flake.lock, tools/flake.nix
Also update ruff in pre-commit
=> Update gemdash tests

src/gemdat/plots/plotly/_density.py
=> Fix number of colors for plot_points

src/gemdat/volume.py
Fix #202 by using the constant from scipy
=> Use kBoltzmann from scipy

CITATION.cff
=> Add Simone to CITATION.cff

src/gemdat/sites.py, tests/integration/sites_test.py
=> Fix mismatch with i variable in activation_energies

src/gemdat/shape.py, tests/shape_test.py
This is a small PR that follows up on #224 to fix some minor issues and makes the api a bit easier to use.
=> Fix issues and tweak api for ShapeAnalyzer

.github/workflows/tests.yaml, README.md
Update coverage badge to directly render svg.
=> Use svg covbadge

src/gemdat/jumps.py, tests/integration/sites_test.py
This PR changes some return types to pandas dataframes.
Closes #249
=> Turn Jumps.rates and Jumps.activation energies into dataframes

pyproject.toml, src/gemdat/legacy.py, src/gemdat/plots/__init__.py, src/gemdat/plots/matplotlib/__init__.py, src/gemdat/plots/matplotlib/_displacements.py, src/gemdat/plots/plotly/__init__.py, src/gemdat/plots/plotly/_displacements.py, src/gemdat/plots/plotly/_jumps.py, src/gemdat/plots/plotly/_vibration.py, src/gemdat/trajectory.py, tests/integration/plot_test.py, tools/flake.lock, tools/flake.nix
Also fixed plot name of displacments_per_site to be displacements_per_atom
Closes #260
=> Added some plotly plots

.github/workflows/code-style.yml, .github/workflows/publish.yaml, .github/workflows/tests.yaml
- Add test on Python 3.12
- Remove wild @v1kko version bumps
=> Update actions versions

CITATION.cff, README.md, pyproject.toml
=> Add zenodo link and how to cite

.github/workflows/tests.yaml, .pre-commit-config.yaml, pyproject.toml
Some minor housekeeping updates to the repo
=> Housekeeping

.pre-commit-config.yaml, src/gemdat/plots/matplotlib/_energy_along_path.py, src/gemdat/plots/matplotlib/_frequency_vs_occurence.py, src/gemdat/plots/matplotlib/_jumps_vs_time.py, src/gemdat/plots/matplotlib/_msd_per_element.py, src/gemdat/plots/matplotlib/_shape.py, src/gemdat/plots/plotly/_msd_per_element.py, src/gemdat/trajectory.py, tests/trajectory_test.py
#47 
I uploaded gromacs data to test_data repository. 
I uploaded here the notebook test_gromacs_support.txt where I tested function from_gromacs. It seems working fine, but I have some concerns:
- I didn't add cache support to the function
- It's a bit weird when extracting structure. Structure information starts from some line not lattice (see the notebook). But lattice works.
- I'm using site_properties attribute of Trajectory to introduce residues
- It could be cool to have opportunity to filter trajectory by residue (see the notebook)
- I got out_of_memory problem when plotting msd from large simulation
[msd.csv](https://github.com/user-attachments/files/16195323/msd.csv)
[test_gromacs_support.txt](https://github.com/user-attachments/files/16195325/test_gromacs_support.txt)
=> Add GROMACS support

.github/workflows/tests.yaml
This PR fixes the coverage badge.
=> Fix coverage badge

src/gemdat/rdf.py
Change specie_1 to specie_2 in str2
=> Correct label in radial_distribution_between_species

src/gemdat/trajectory.py
This PR expands io capabilities for the lammps reader in GEMDAT. See #353 for more information.
Usage:
```python
traj = from_lammps(
coords_file='trajectory.xyz',
data_file='in.data',
temperature=1000,
time_step=0.001,
type_mapping={'1':'Li', '2':'S', '3':'O'},
coords_format= 'xyz',
atom_style='full'
)
traj = from_lammps(
coords_file='trajectory.dump',
data_file='in.data',
temperature=1000,
time_step=0.001,
type_mapping={'1':'Li', '2':'S', '3':'O'},
coords_format= 'lammpsdump',
atom_style='full'
)
```
Closes #353
=> Work-around for atoms without label when reading lammps data

src/gemdat/plots/matplotlib/_shape.py, src/gemdat/plots/plotly/_plot3d.py, src/gemdat/plots/plotly/_shape.py
Add cmap option to plotly plot.
=> Add cmap option to plotly shape function

README.md
=> Update citation listing

README.md
This PR adds the Lorentz workshop PDF to the Readme.
=> Add pdf for workshop to readme
