- src/calculate/displacements.py
- src/calculate/tracer.py
- src/calculate/vibration.py
- src/dashboard/run.py
- src/data.py
- src/sites.py
- tests/integration_test.py
This PR revises the way extras are handled and passes them around as a `SimpleNamespace`. This makes it a bit easier to pass them around and get the attribrutes. We can convert this to a class/dataclass at a later stage if necessary.
The `calculate_all` now expect `data` + `extras` but they still return dicts with the data which are then added to `extras`.
> Revise extras

- src/sites.py
- src/utils.py
- tests/integration_test.py
- tests/utils_test.py
In the matlab code, the location of each atom is tracked through `sites.atom_sites`. The index corresponds to a number that is generated on the fly. The states are in a different array called `sites.site_names`.
This array contains these values:
- `48h` : Atom is currently sitting at this site
- `Transition:48h` : Atom is currently in transition, but will go back to itself (48h)
- `Transition:48h-48h` : Atom is currently in transition from 48h to another site named 48h
The index in `atom_sites` corresponds to en element in `sites.site_names` containing these values.
I have taken a different approach. For each time step, I calculate the index of the current, previous and next site. `atom_sites` tracks the index of the site the atom is currently at. `-1` indicates the atom is in transition. …
> Calculate origin and destination sites for atoms in transition

- src/sites.py
- tests/integration_test.py
This PR refactors how parts are being calculated on `SitesData`. This avoid the use of custom code for the parts, and makes use of existing methods on `SitesData` where possible.
Closes #34
> Refactor `SitesData`

- src/legacy.py
- src/sites.py
This PR adds a legacy Python api call (`gemdat.legacy.analyse_md`) function to mimick the matlab code.
```python
from gemdat.legacy import analyse_md
data, sites, extras = analyse_md(
'~/md-analysis-matlab-example/vasprun.xml',
diff_elem='Li',
supercell=(2,1,1),
material='argyrodite',
)
```
> Add legacy interface to mimick matlab code

- src/__init__.py
- src/calculate/__init__.py
- src/calculate/displacements.py
- src/calculate/extras.py
- src/calculate/tracer.py
- src/calculate/vibration.py
- src/dashboard/_shared.py
- src/dashboard/run.py
- src/data.py
- src/legacy.py
- src/plot.py
- src/plots/displacements.py
- src/plots/jumps.py
- src/rdf.py
- src/sites.py
- src/trajectory.py
- src/volume.py
- tests/displacement_test.py
- tests/integration_test.py
- tests/tracer_test.py
- tests/vibration_test.py
In this PR I'm exploring `pymatgen.core.trajectory.Trajectory` to see if we can use that instead of `SimulationData`. It seems that everything we need is more or less available from this object alone. 
The goal is to replace `SimulationData` as the data structure, and use `Trajectory` instead. To start, I am making this a subclass to see what we need to do to get this to work.
One of the challenges will be to structure the data in such a way that we can drag along all the `extras`.
Addresses part of #67
Also helps with #62
> Use `Trajectory` in place of `SimulationData`

- README.md
- src/__init__.py
- src/calculate/extras.py
- src/calculate/tracer.py
- src/dashboard/run.py
- src/legacy.py
- src/rdf.py
- src/sites.py
- src/trajectory.py
- src/volume.py
- tests/conftest.py
- tests/displacement_test.py
- tests/integration_test.py
- tests/tracer_test.py
- tests/trajectory_test.py
- tests/vibration_test.py
Adds filter method from #94 to `Trajectory` class.
In addition:
- Revises code using `diff_coords` to use `.filter()` instead
- Adds a metadata attribute to store arbitrary information about the trajectory.
- Adds trajectory tests
- Updates test to re-use shared trajectory fixture
Closes #67
> Add filter method to Trajectory

- pyproject.toml
Point to pymatgen repo instead of an (outdated) branch on my fork
> Update pymatgen requirement in pyproject.toml

- src/calculate/displacements.py
- src/calculate/extras.py
- src/plots/displacements.py
- src/rdf.py
- src/sites.py
- src/trajectory.py
- src/volume.py
- tests/trajectory_test.py
This PR adds a drift correction method to `Trajectory`.
```python
drift = trajectory.drift(fixed_species=('Br', 'P', 'S'))
drift = trajectory.drift(floating_species='Li')
drift_corrected = trajectory.apply_drift_correction(floating_species='Li')
```
Note: I also added methods for getting displacements / positions explicitly to avoid confusion and having to do the `.to_positions()`/`to_displacements()` dance. `displacements` overlaps with one of the values we calculate (`Displacements` class), so we should consider a different name for that one.
Closes #89
> Drift correction

- README.md
- src/collective.py
- src/dashboard/run.py
- src/legacy.py
- src/plots/_jumps.py
- src/rdf.py
- src/simulation_metrics.py
- src/sites.py
- src/transitions.py
- tests/integration/conftest.py
- tests/integration/rdf_test.py
- tests/integration/sites_test.py
- tests/integration/trajectory_test.py
- tests/simulation_metrics_test.py
- tests/sites_test.py
This PR refactors all sites methods into property functions which can be calculated on demand, taking the work from #94 as a starting point.
I got into trouble with the $_parts functions, which did not refactor well. I made a new class called `Transitions`, which stores all the transition data that are the basis for the _parts attributes.
I also moved all code to calculate collections into its own class for better separation, and to make it a bit more ergonomic to work with the data.
> Refactor sites into property-like functions

- src/trajectory.py
This PR allows users to specify keyword arguments to pass to `vasp.Vasprun`. This can overcome issues with incomplete or unfinished xml files, by setting `exception_on_bad_xml=False`, for example.
Closes #113
> Pass user keyword arguments to `vasp.Vasprun` initializer

- pyproject.toml
- src/volume.py
- tests/integration/trajectory_test.py
This PR adds a new function `volume.volume_to_structure` that takes a volume, finds the peaks using image segmentation, and returns a `Structure` object.
```python
from gemdat import Trajectory
from gemdat.volume import trajectory_to_volume
from gemdat.volume import volume_to_structure
trajectory = Trajectory.from_vasprun('/home/stef/md-analysis-matlab-example/vasprun.xml')
trajectory = trajectory.filter('Li')
vol = trajectory_to_volume(trajectory)
structure = volume_to_structure(
vol, 
lattice=trajectory.get_lattice(), 
specie='Li',
cif_filename='structure.cif',
vol_filename='structure.vol',
)
```
Closes #45
> Derive sites from trajectory (or other) density

- src/gemdat/segmentation.py
- src/gemdat/volume.py
- tests/integration/trajectory_test.py
- tests/segmentation_test.py
I'm investigating what is the cause for #138. I refactored the two `Volume.to_structure()` methods to share code. I added a failing test for what I think is the cause of the problem:
The watershed implementation works with flattened arrays, which means you get 'free' wrapping around in the horizontal directions, although not quite, because by wrapping around it would shift one row up or down. Once you reach there end of the flattened array, this falls appart, because once you hit the last rows, the connectivity structure potentially hits unbound memory (The function has `@cython.boundscheck(False)`).
---
I reverted part of #130 that changed the watershed implementation to deal with pbc. Now it uses padding again, this is a bit less memory efficient, but it works and passes the tests …
> Refactor `Volume.to_structure` and revert to padded watershed for pbc

- src/gemdat/trajectory.py
This PR does two things:
- It might happen that runs are incomplete, if this happens add a helpful message for hinting that this might be the case, and how to resolve it #157 
- Append the kwargs to the cache path, because using different kwargs will result in different caches, this links to issue #158 
- Issue: this leads to very long filenames, it might be possible to store this info _inside_ the cache instead, so this comparison can still be done, and the cache can be refreshed on keyword changes.  however this would require some thought, and this solution is much simpler
> Added descriptive error on loading incomplete xml file, append kwargs to cache path

- src/gemdat/simulation_metrics.py
- src/gemdat/transitions.py
Sometimes nparts does not evenly divide an array, but for us this is okay, we can work with uneven arrays. Therefore we replace np.split with np.array_split
> Allow uneven splits with np.array_split

- src/gemdat/plots/_density.py
#160 
Fix the lattice mismatch between Volume and Structure, change Structure to optional argument, create structure coords using Volume, make equal sites same color
> Tweak density plotting function

- src/gemdat/plots/_density.py
I noticed it was hardcoded to 2,1,1 . So I changed it to `lattice.abc` also adjusted the "eye" location to provide a view relative to `lattice.abc` instead of 2,1,1
> Make sure the aspect ratio of the density plot is similar to the volume

- docs/dashboard.md
- src/gemdat/dashboard/gemdash.py
- src/gemdat/dashboard/run.py
This pull request adds the optional `--file [FILE]` argument to `gemdash`
> Add optional argument to gemdash, to specify trajectory location

- src/gemdat/io.py
Apparently it is not possible to fix the warning, so I'm hiding it.
This PR also moves to the recommended way to read/write cif files.
Closes #221
> Hide warning when loading a cif file through pymatgen

- src/gemdat/plots/plotly/_density.py
- src/gemdat/shape.py
This PR makes gemdat a bit more flexible to specify custom lattices.
Closes #198
> Allow custom lattice for density plot and `ShapeAnalyzer`

- src/gemdat/plots/matplotlib/_shape.py
- src/gemdat/shape.py
- tests/shape_test.py
This PR adds a sites argument to `plots.shape()`.
Closes #200
```python
shape = shapes[0]
sites = structure.get_sites_in_sphere(pt=shape.origin, r=radius)
plots.shape(shape, bins=bins, sites=sites)
```
> Add function to display sites on shape plot

- src/gemdat/jumps.py
- tests/integration/jumps_test.py
> jumps calculation: switched joined prerequisites to independent prerequisites

- src/gemdat/jumps.py
- src/gemdat/legacy.py
- src/gemdat/sites.py
- src/gemdat/trajectory.py
- src/gemdat/transitions.py
- tests/integration/sites_test.py
This PR changes how the occupancies are returned. The currently returned as a dictionary with indexes, which is inconvenient. This PR changes the return type to a Structure, with the occupancies set through the composition.
Closes #244
> Return structure with occupancy set as Composition

- src/gemdat/jumps.py
- src/gemdat/transitions.py
- tests/integration/sites_test.py
This PR proposes a possible fix for #252. I believe diff_trajectory must be stored on Transitions instead of Trajectory.
Closes #252
> Fix wrong `n_floating` bug

- src/gemdat/transitions.py
- src/gemdat/utils.py
- tests/integration/transitions_test.py
This PR tweaks the Transitions class a bit after #251.
- Fix bug in stdout
- Rename dist_close -> site_radius
- Add `gemdat.utils.VASPRUN` to access test data for notebooks
> Small tweaks to Transitions

- src/gemdat/trajectory.py
- src/gemdat/transitions.py
- src/gemdat/utils.py
- tests/integration/transitions_test.py
- tests/utils_test.py
This PR adds support for per site type radii.
This requires flipping the KDTree in `_calculate_atom_states`. Generate the kdtree with the trajectory, and query using the sites. The cutoff for the kdtree is set to the maximum distance in the site radius dict. The search tree radius is set to the current site.
The sites are grouped by label, so for each group of sites the kdtree needs to be queried.
Closes #234
> Calculate transitions with custom radii per site type

- README.md
- src/gemdat/simulation_metrics.py
- src/gemdat/trajectory.py
- tests/integration/trajectory_test.py
This PR implements Haven's ratio as described here: https://github.com/GEMDAT-repos/GEMDAT/issues/269#issuecomment-1991636949
You call it it via `SimulationMetrics.haven_ratio()`
Closes #269
> Implement Haven ratio

- src/gemdat/rotations.py
- src/gemdat/simulation_metrics.py
- tests/integration/plot_test.py
- tests/integration/rotations_test.py
- tests/integration/trajectory_test.py
- tests/rotations_test.py
This PR makes some small changes to the code after discussions with @v9lgraf @tfamprikis 
1. Rename `ionic_conductivity` to `tracer_diffucivity_center_of_mass`. 
2. Set default `dimensions=3` (it can still be configured)
3. Rename `Orientations.conventional()` -> `Orientations.transform()`
> Tweak method names and update default dimensions

- src/gemdat/plots/matplotlib/_autocorrelation.py
- src/gemdat/plots/matplotlib/_msd_per_element.py
> Add option to show shaded area for std

- docs/api/gemdat_legacy.md
- mkdocs.yml
- scripts/analyse_md.py
This PR moves the legacy interface to its own file mimicking analyse_md from the matlab code.
Closes #314
> Move legacy.py out of main library

- src/gemdat/__init__.py
- src/gemdat/plots/__init__.py
- src/gemdat/rdf.py
- src/gemdat/transitions.py
This PR makes it easier to calculate and plot RDFs.
```python
rdf_data = transitions.radial_distribution(
floating_specie='Li',
)
for rdfs in rdf_data.values():
fig = rdfs.plot()
fig.show()
```
Closes https://github.com/GEMDAT-repos/gemdat-notebooks/issues/12
> Add shortcut for calculating and plotting RDFs

- README.md
- src/gemdat/trajectory.py
- tests/trajectory_test.py
This PR implements a lammps reader for #47
> Add LAMMPS trajectory reader

- pyproject.toml
- scripts/analyse_md.py
- src/gemdat/io.py
- src/gemdat/jumps.py
- src/gemdat/orientations.py
- src/gemdat/path.py
- src/gemdat/plots/_shared.py
- src/gemdat/plots/matplotlib/_msd_per_element.py
- src/gemdat/plots/plotly/_msd_per_element.py
- src/gemdat/plots/plotly/_plot3d.py
- src/gemdat/rdf.py
- src/gemdat/shape.py
- src/gemdat/trajectory.py
- src/gemdat/volume.py
> Fix all mypy issues

- src/gemdat/transitions.py
- tests/integration/transitions_test.py
This PR adds a  work-around when `Transitions.occupancy` is called, but the input sites are disordered. Disordered jump sites technically do not make sense, but the code only works with the coordinates anyway.
Closes #339
> Fix crash in `Transitions.occupancy` if input sites are disordered

- src/gemdat/transitions.py
This PR fixes a crash if no near atoms were found in the periodic search tree. It now checks for a null result and adds a warning. I also refactored the code slightly.
Closes #352
> Add warning if there are no species in range of site

- src/gemdat/transitions.py
> Add flag to set all occupancies to 1

- src/gemdat/trajectory.py
- src/gemdat/transitions.py
- src/gemdat/utils.py
- tests/utils_test.py
This PR changes how disordered species are handled by `Transitions`. It now raises an error, because the analysis does not work with disordered species. I also added this `Transitions.from_trajectory`), so it now breaks at the earliest possible stage. I added a function `gemdat.utils.remove_disorder_from_species` to help 'fix' the structure. 
This fixes 2 issues with the current code:
1. The current code updates `sites` in-place. This can give unintended side effects
2. There is better separation of concerns. This changes allows the user to inspect the `sites` before using the `Transitions` code. This prevents unwanted changes to the structure and places control for making sure the structure is what they wanted with the users.
Usage:
```python
from gemdat.utils import …
```
> Raise error when disordered structure is passed to `Transitions`

- src/gemdat/jumps.py
- tests/integration/jumps_test.py
it is now correctly taken into account
> fix the error in the jumps calculation with minimal_residence
